// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Blog Post documents */
interface BlogPostDocumentData {
    /**
     * Titulo field in *Blog Post*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * date_publisher field in *Blog Post*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.date_publisher
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    date_publisher: prismicT.DateField;
    /**
     * Imagem de Destaque field in *Blog Post*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.cover
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover: prismicT.ImageField<never>;
    /**
     * seo_description field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.seo_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_description: prismicT.KeyTextField;
    /**
     * seo_keywords field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.seo_keywords
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_keywords: prismicT.KeyTextField;
    /**
     * seo_title field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.seo_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Blog Post*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    body: prismicT.SliceZone<BlogPostDocumentDataBodySlice>;
}
/**
 * Primary content in Blog Post → Slice Zone → `teste` → Primary
 *
 */
interface BlogPostDocumentDataBodyTesteSlicePrimary {
    /**
     * Texto field in *Blog Post → Slice Zone → `teste` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.body[].teste.primary.texto
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    texto: prismicT.RichTextField;
}
export type BlogPostDocumentDataBodyTesteSlice = prismicT.Slice<"teste", Simplify<BlogPostDocumentDataBodyTesteSlicePrimary>, never>;
/**
 * Primary content in Blog Post → Slice Zone → `code` → Primary
 *
 */
interface BlogPostDocumentDataBodyCodeSlicePrimary {
    /**
     * Code field in *Blog Post → Slice Zone → `code` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.body[].code.primary.code
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    code: prismicT.RichTextField;
}
export type BlogPostDocumentDataBodyCodeSlice = prismicT.Slice<"code", Simplify<BlogPostDocumentDataBodyCodeSlicePrimary>, never>;
/**
 * Slice for *Blog Post → Slice Zone*
 *
 */
type BlogPostDocumentDataBodySlice = BlogPostDocumentDataBodyTesteSlice | BlogPostDocumentDataBodyCodeSlice;
/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BlogPostDocumentData>, "blog_post", Lang>;
/** Content for Blog Post documents */
interface BlogPostDocumentData {
    /**
     * Titulo field in *Blog Post*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * date_publisher field in *Blog Post*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.date_publisher
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    date_publisher: prismicT.DateField;
    /**
     * Imagem de Destaque field in *Blog Post*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.cover
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    cover: prismicT.ImageField<never>;
    /**
     * seo_description field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.seo_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_description: prismicT.KeyTextField;
    /**
     * seo_keywords field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.seo_keywords
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_keywords: prismicT.KeyTextField;
    /**
     * seo_title field in *Blog Post*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.seo_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Blog Post*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.body[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    body: prismicT.SliceZone<BlogPostDocumentDataBodySlice>;
}
/**
 * Primary content in Blog Post → Slice Zone → `teste` → Primary
 *
 */
interface BlogPostDocumentDataBodyTesteSlicePrimary {
    /**
     * Texto field in *Blog Post → Slice Zone → `teste` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.body[].teste.primary.texto
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    texto: prismicT.RichTextField;
}
export type BlogPostDocumentDataBodyTesteSlice = prismicT.Slice<"teste", Simplify<BlogPostDocumentDataBodyTesteSlicePrimary>, never>;
/**
 * Primary content in Blog Post → Slice Zone → `code` → Primary
 *
 */
interface BlogPostDocumentDataBodyCodeSlicePrimary {
    /**
     * Code field in *Blog Post → Slice Zone → `code` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: blog_post.body[].code.primary.code
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    code: prismicT.RichTextField;
}
export type BlogPostDocumentDataBodyCodeSlice = prismicT.Slice<"code", Simplify<BlogPostDocumentDataBodyCodeSlicePrimary>, never>;
/**
 * Slice for *Blog Post → Slice Zone*
 *
 */
type BlogPostDocumentDataBodySlice = BlogPostDocumentDataBodyTesteSlice | BlogPostDocumentDataBodyCodeSlice;
/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BlogPostDocumentData>, "blog_post", Lang>;
export type AllDocumentTypes = BlogPostDocument | BlogPostDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { BlogPostDocumentData, BlogPostDocumentDataBodyTesteSlicePrimary, BlogPostDocumentDataBodyTesteSlice, BlogPostDocumentDataBodyCodeSlicePrimary, BlogPostDocumentDataBodyCodeSlice, BlogPostDocumentDataBodySlice, BlogPostDocument, AllDocumentTypes };
    }
}
